# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_name=Genesis
mod_id=genesis
mod_version=1.5.0
mod_authors=uhmbyee / Mariany Pinkston
mod_description=Adds more friction to Minecraft's progression system.
mod_page_url=https://curseforge.com/minecraft/mc-mods/genesis-official
mod_git_url=https://github.com/marianyp/Genesis
mod_license=ARR

maven_group=dev.mariany.genesis
archives_base_name=genesis

# Dependencies
fabric_version=0.138.3+1.21.10
genesis_framework_version=1.0.6
rei_version=21.9.812